package com.zongbutech.httplib.http.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zongbutech.httplib.http.db.ChatRoomBean;

import com.zongbutech.httplib.http.db.ChatRoomBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatRoomBeanDaoConfig;

    private final ChatRoomBeanDao chatRoomBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatRoomBeanDaoConfig = daoConfigMap.get(ChatRoomBeanDao.class).clone();
        chatRoomBeanDaoConfig.initIdentityScope(type);

        chatRoomBeanDao = new ChatRoomBeanDao(chatRoomBeanDaoConfig, this);

        registerDao(ChatRoomBean.class, chatRoomBeanDao);
    }
    
    public void clear() {
        chatRoomBeanDaoConfig.getIdentityScope().clear();
    }

    public ChatRoomBeanDao getChatRoomBeanDao() {
        return chatRoomBeanDao;
    }

}
